micronaut:
  application:
    name: taskman
  server:
    port: 8888
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - "http://localhost:5174"
          allowedMethods:
            - "GET"
            - "POST"
            - "PUT"
            - "DELETE"
            - "OPTIONS"
            - "PATCH"
          allowedHeaders:
            - "Authorization"
            - "Content-Type"
            - "Accept"
            - "Origin"
            - "X-Requested-With"
            - "Access-Control-Request-Method"
            - "Access-Control-Request-Headers"
          exposedHeaders:
            - "Authorization"
            - "Content-Type"
          allowCredentials: true
          maxAge: 3600
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET:pleaseChangeThisSecretForANewSecretAndMakeItSecure}
              jws-algorithm: HS256
        generator:
          access-token:
            expiration: 86400  # 1 day in seconds
    endpoints:
      login:
        path: /api/auth/login  # Override the default /login path
        enabled: true
        path: /api/auth/login
      oauth:
        enabled: true
      logout:
        path: /api/auth/logout  # Override the default /logout path
        enabled: true
    intercept-url-map:
      - pattern: /api/tasks/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /api/categories/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /api/auth/login
        httpMethod: POST
        access:
          - isAnonymous()
      - pattern: /api/auth/register
        httpMethod: POST
        access:
          - isAnonymous()
      - pattern: /api/auth/check-token
        httpMethod: GET
        access:
          - isAnonymous()

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/taskman`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver

flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

endpoints:
  health:
    enabled: true
    sensitive: false